### ISSUE TITLE
Reject instead of resolve(null) when `mustBeMetamask` is true 

### ISSUE THREAD

**Issue by GabrielBuragev** [MetaMask/metamask-onboarding#101]
# Rationale
There are times when multiple wallet provider extensions are installed inside the users browser alongside MetaMask.
Some extensions play together nicely (for example Metamask & Coinbase) but some are simply overwriting the `window.ethereum` property with their own injection (for example Metamask & Frame Companion).

In these cases, i would like to be able to call `await detectEthereumProvider({mustBeMetamask: true})` and get a rejection if no MetaMask was found at `window.ethereum` instead of a null resolution.

**Comment by mcmire** [comment]
Hi @GabrielBuragev, the `detectEthereumProvider` function is provided by our [`detect-provider` library](https://github.com/MetaMask/detect-provider). Perhaps you meant to post this issue there?

**Comment by GabrielBuragev** [comment]
Oh ... really sorry. Will move this issue there, thanks for the heads up!

**Comment by mcmire** [comment]
No problem! I see the new issue so I'll close this :)
