### ISSUE TITLE
Missing exports warning from `yarn build`

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/metamask-onboarding#46]
The following warning is produced from `yarn build`:

```bash
$ yarn build
```
```
yarn run v1.22.4
$ rollup --config

src/index.ts → dist/metamask-onboarding.cjs.js, dist/metamask-onboarding.es.js...
created dist/metamask-onboarding.cjs.js, dist/metamask-onboarding.es.js in 1s

src/index.ts → dist/metamask-onboarding.bundle.js...
(!) Missing exports
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/index.ts
parse is not exported by node_modules/bowser/src/bowser.js
175: 
176:   static _detectBrowser () {
177:     const browserInfo = Bowser.parse(window.navigator.userAgent);
                                    ^
178:     if (browserInfo.browser.name === 'Firefox') {
179:       return 'FIREFOX';
created dist/metamask-onboarding.bundle.js in 708ms
```

And we do have a `namedExports` option defined for cjs:

https://github.com/MetaMask/metamask-onboarding/blob/c476b69af5da0420c8b614e7e586f33c50003e40/rollup.config.js#L32-L36

**Comment by KupoSteve** [comment]
I have the exact same issue. Any work arounds?

**Comment by nickfla1** [comment]
We resolved the changing the import line in index.ts from:
```ts 
import * as Bowser from 'bowser';
```
to:
```ts 
import Bowser from 'bowser';
```

and settings `allowSyntheticDefaultImports` to `true` inside tsconfig.json (_compilerOptions_).

Hope someone will find this useful.

**Comment by felixakiragreen** [comment]
@nickfla1 did you patch the package?

**Comment by trapped** [comment]
Just stumbled upon this after noticing that in the current 1.0.0 npm package's `dist/metamask-onboarding.bundle.js` file, `Bowser.parse` appears to have been replaced by `undefined`, effectively breaking the package.

**Comment by nickfla1** [comment]
@felixakiragreen I needed the browser bundle file so I just updated my cloned repository before running yarn build. 
I can craft a PR with my changes.

**Comment by trapped** [comment]
@nickfla1 just opened a PR with your changes.
