### ISSUE TITLE
Enhancement Request: Make The Onboarding Destructurable

### ISSUE THREAD

**Issue by BboyAkers** [MetaMask/metamask-onboarding#50]
Importing MetaMask Onboarding into a project looks like this.
```javascript
import MetaMaskOnboarding from '@metamask/onboarding'
```
Suggested Enhancement:
```javascript
import { MetaMaskOnboarding, IsMetaMaskInstalled }  from '@metamask/onboarding'
```
It would be great to put the onboarding process as an exportable module and decouple the `isMetaMaskInstalled()` function into it's own exportable module.

Implementing this would reduce on declaration redundancy in business logic for applications that import this module.
Example: MetaMask/test-dapp [line 40](https://github.com/MetaMask/test-dapp/blob/master/src/index.js#L40).
```javascript
const isMetaMaskInstalled = () => {
  const { ethereum } = window
  return Boolean(ethereum && ethereum.isMetaMask)
}
```
Setback: Applications that use this onboarding module will have to do a small refactor.

Side note: 
- I haven't tested it but i'm sure it's possible to MetaMaskOnboarding().isMetaMaskInstalled() in the test dapp and/or applications that implement `'@metamask/onboarding'` . I'm just not a big fan of repetitive declarations to see if MetaMask is installed or not.

Thoughts? @whymarrh 

If you all agree this would be great i'd be more than willing to take this on.

**Comment by whymarrh** [comment]
> Example: MetaMask/test-dapp line 40.

The `isMetaMaskInstalled` method defined in the test-dapp is redundant, yup. I think thought that we can already update the test dapp to use `MetaMaskOnboarding.isMetaMaskInstalled()` without any changes to the codebase here, something like so:

```diff
-    const accountButtonsDisabled = !isMetaMaskInstalled() || !isMetaMaskConnected()
+    const accountButtonsDisabled = !MetaMaskOnboarding.isMetaMaskInstalled() || !isMetaMaskConnected()
```

We could also shorten that by destructuring the static method on line 40, in place of the existing method:

```diff
 import MetaMaskOnboarding from '@metamask/onboarding'
 
 const currentUrl = new URL(window.location.href)
 const forwarderOrigin = currentUrl.hostname === 'localhost'
   ? 'http://localhost:9010'
   : undefined

-const isMetaMaskInstalled = () => {
-  const { ethereum } = window
-  return Boolean(ethereum && ethereum.isMetaMask)
-}
+const { isMetaMaskInstalled } = MetaMaskOnboarding
```

I think that should work?

**Comment by BboyAkers** [comment]
Gotcha, thanks man! I'll close this issue! Appreciate the clarification!
