### ISSUE TITLE
How to check if metamask is connected to site

### ISSUE THREAD

**Issue by vijaytabhatt** [MetaMask/metamask-onboarding#62]
How to check if metamask is connected to site

**Comment by drachs** [comment]
`accounts = await ethereum.request({ method: 'eth_accounts' })
    if (_accounts.length === 0) {
        console.log("Metamask is Disconnected");
    } else {
        console.log("Metamask is Connected");
        accounts = _accounts;     
    }
}

`

**Comment by Gudahtt** [comment]
Thanks @drachs for answering this!

@vijaytabhatt please post in our community forum if you have any further questions: https://community.metamask.io/
