### ISSUE TITLE
Cannot npm install

### ISSUE THREAD

**Issue by bbugs280** [MetaMask/metamask-onboarding#87]
Hi all, I'm trying to run: 

npm install @metamask/onboarding 

But getting the following error, Anyone can help?

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/vincent/Documents/DApp/metamask-onboarding-main/node_modules/@lavamoat/preinstall-always-fail
npm ERR! command failed
npm ERR! command sh -c echo "Don't run npm lifecycle scripts by default, whitelist them with @lavamoat/allow-scripts" && exit 1
npm ERR! Don't run npm lifecycle scripts by default, whitelist them with @lavamoat/allow-scripts

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vincent/.npm/_logs/2022-02-20T09_03_27_652Z-debug-0.log

**Comment by gabriellahayden** [comment]
Are you still having issues with npm install?

**Comment by mcmire** [comment]
Hi @bbugs280 — a bit late here, I admit, but it looks like you're having an issue with `@lavamoat/allow-scripts`. It would help us if you posted your `package.json`.
